import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      status: 'admin'
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      status: 'member',
    },
  ],
  products: [
    {
      name: 'Avocado, Large',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/avocado_dzlpve.png',
      price: .69,
      stock:55,
      desc: '1 ct',

    },
    {
      name: 'Cucumbers',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/Cucumbers_tgmdlm.png',
      price: 1.20,
      stock:66,
      desc: '1 ct',

    },
    {
      name: 'Green Bell Pepper',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/GreenBellPepper_osd0k5.webp',
      price: .39,
      stock:36,
      desc: '1 ct',

    },
    {
      name: 'Onion Red',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/OnionRed_lb82et.webp',
      price: 1.09,
      stock:68,
      desc: '1 ct',
    },
    {
      name: 'Eggplant',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/veges/Eggplant_oqmxtd.webp',
      price: 1.19,
      stock:21,
      desc: '1 ct',
    },
    {
      name: 'Yams Red',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/yamsred_sieqfg.webp',
      price: .79,
      stock:44,
      desc: '1 ct',
    },
    {
      name: 'Green Giant Fresh Carrots',
      tags: ['vegetables'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/veges/GreenGiantFreshCarrots_p6vrjx.webp',
      price: .89,
      stock: 10,
      desc: '1 lb',
    },
    // fruits
    {
      name: 'Watermelons Seedless',
      tags: ['fruits'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/fruits/WatermelonsSeedless_qqyiha.png',
      price: 1.89,
      stock:33,
      desc: '1 ct',
    },
    {
      name: 'Large Mangos',
      tags: ['fruits'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/mango_acl4iz.png',
      price: .89,
      stock:32,
      desc: '1 ct',
    },
    {
      name: 'Honeydew',
      tags: ['fruits'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/honeydew_anhihd.webp',
      price: 1.59,
      stock:13,
      desc: '1 ct',
    },
    {
      name: 'Pears Bartlett',
      tags: ['fruits'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/PearsBartlett_cx5bbo.webp',
      price: .89,
      stock:55,
      desc: '1 ct',
    },
    {
      name: 'Sweet Limes',
      tags: ['fruits'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/fruits/SweetLimes_mz6a9e.webp',
      price: .69,
      stock:23,
      desc: '1 ct',
    },
    // meat
    {
      name: 'Chicken Breast Bnls Skinless',
      tags: ['meat'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/chickenbreast_nw9nug.webp',
      price: 3.49,
      stock:12,
      desc: '1 pkg',
    },
    {
      name: 'Chicken Drumsticks',
      tags: ['meat'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/chickendrumsticks_hvur9o.webp',
      price: 1.99,
      stock:43,
      desc: '1 pkg',
    },
    {
      name: 'Buddig Original Deli Thin Beef',
      tags: ['meat'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/BuddigOriginalDeliThinBeef_ildno9.webp',
      price: .89,
      stock:52,
      desc: '1 pkg',
    },
    {
      name: 'Chicken Thighs',
      tags: ['meat'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/ChickenThighs_oamvvc.jpg',
      price: 5.97,
      stock:12,
      desc: '1 pkg',
    },
    {
      name: 'Cacique Pork Chorizo',
      tags: ['meat'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/meat/caciqueporkchorizo_lqzxnk.webp',
      price: 1.19,
      stock:23,
      desc: '1 pkg',
    },
    // dairy
    {
      name: 'Egglands Best Organic Cage Free Grade A Brown Eggs',
      tags: ['dairy'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/egglandegg_hu5mb8.webp',
      price: 6.39,
      stock:25,
      desc: '12 ct',
    },
    {
      name: 'Horizon Organic 2% Milk',
      tags: ['dairy'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/horizonmilk_qvp6as.webp',
      price: 4.99,
      stock:26,
      desc: '1/2 gal',
    },
    {
      name: 'Yoplait Original Yogurt Harvest Peach Tub',
      tags: ['dairy'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/dairy/yoplaitorginalyogurtharvest_agfu6w.webp',
      price: 3.49,
      stock:21,
      desc: '32 oz',
    },
    {
      name: 'Shamrock Farms Vitamin D Whole Milk',
      tags: ['dairy'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/shamrockfarmsvitamind_nr2pcg.webp',
      price: 4.69,
      stock:12,
      desc: '1 gal',
    },
    {
      name: 'Chobani Plain Non-Fat Greek Yogurt',
      tags: ['dairy'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/chobaniplannonfat_ol4ba5.webp',
      price: 5.70,
      stock:43,
      desc: '32 oz',
    },
    {
      name: 'Challenge Butter',
      tags: ['dairy'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668306/dairy/ChallengeButter_fhneqp.webp',
      price: 5.29,
      stock: 10,
      desc: '16 oz',
    },
    {
      name: 'SuperPretzel Baked Soft Pretzels',
      tags: ['frozen'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/superpretzel_btxubb.webp',
      price: 4.09,
      stock: 10,
      desc: '6 ct',
    },
    {
      name: 'Kelloggs Eggo Waffles Homestyle',
      tags: ['frozen'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/kellogg_zaxhdn.webp',
      price: 2.89,
      stock: 10,
      desc: '10 ct',
    },
    {
      name: 'Red Baron Pizzeria Style Classic Crust Pepperoni Pizza',
      tags: ['frozen'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668308/frozen/redbaronclassiccrust_ukezr8.webp',
      price: 4.09,
      stock: 10,
      desc: '20 oz',
    },
    {
      name: 'Cool Whip Original Whipped Topping',
      tags: ['frozen'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/coolwhip_morivm.webp',
      price: 4.69,
      stock: 10,
      desc: '16 oz',
    },
    {
      name: 'El Monterey Beef & Bean Burritos',
      tags: ['frozen'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668307/frozen/elmontererybeef_wbtflj.webp',
      price: 4.69,
      stock: 10,
      desc: '8 ct',
    },
    // pantry
    {
      name: 'Kraft Original Flavor Macaroni and Cheese',
      tags: ['pantry'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/kraft_lcsmiu.webp',
      price: 1.49,
      stock: 10,
      desc: '7.25 oz',
    },
    {
      name: 'Rotel Original Diced Tomatoes & Green Chilies',
      tags: ['pantry'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/rotel_g2hzjo.webp',
      price: 1.49,
      stock: 10,
      desc: '12 oz',
    },
    {
      name: 'Cinnamon Toast Crunch Cereal - General Mills',
      tags: ['pantry'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/cinnamon_zitdrc.webp',
      price: 5.79,
      stock: 10,
      desc: '19.3 oz',
    },
    {
      name: 'Jiffy Corn Muffin Mix - 8.5',
      tags: ['pantry'],
      image: '/assets/pantry/jiffy.webp',
      price: .89,
      stock: 10,
      desc: '8.5 oz',
    },
    {
      name: 'Jif Creamy Peanut Butter',
      tags: ['pantry'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/jifcreamypeanutbutter_bwmyn2.webp',
      price: 3.29,
      stock: 10,
      desc: '16 oz',
    },
    {
      name: 'Heinz Easy Squeeze Tomato Ketchup',
      tags: ['pantry'],
      image: 'https://res.cloudinary.com/duaotrdm6/image/upload/v1610668305/pantry/heinz_u3vil3.webp',
      price: 3.79,
      stock: 10,
      desc: '20 oz',
    }
  ],
};
export default data;


